import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import HeroSection from "@/components/HeroSection/HeroSection";
import Navigation from "@/components/Navigation/Navigation";
import ContactSection from "@/components/ContactSection/ContactSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <HeroSection />
      <ContactSection />
    </>
  );
}
